package localization

var l10nDe = l10n{
	// navigation
	payments:        "Zahlungen",
	categories:      "Kategorien",
	analysis:        "Auswertungen",
	debts:           "Schulden",
	expenses:        "Ausgaben",
	by_category:     "Nach Kategorie",
	admin_functions: "Admin-Funktionen",
	users:           "Nutzende",
	projects:        "Projekte",
	// actions
	logout:                          "Ausloggen",
	search:                          "Suchen",
	filter:                          "Filtern",
	date_filter:                     "Nach Datum filtern",
	new:                             "Erstellen",
	edit:                            "Bearbeiten",
	save:                            "Speichern",
	cancel:                          "Abbrechen",
	delete:                          "Entfernen",
	delete_confirmation:             "Löschbestätigung",
	delete_confirmation_description: "Sind Sie sicher, dass Sie dieses Element entfernen wollen? Diese Aktion kann nicht rückgängig gemacht werden.",
	// alerts
	no_records_found:          "Keine Einträge gefunden",
	record_saved_successfully: "Eintrag erfolgreich gespeichert",
	// fields
	id:            "#",
	name:          "Name",
	amount:        "Betrag",
	date:          "Datum",
	category:      "Kategorie",
	color:         "Farbe",
	payer:         "Zahler",
	payee:         "Empfänger",
	description:   "Beschreibung",
	username:      "Benutzername",
	password:      "Passwort",
	role:          "Rolle",
	role_normal:   "Normal",
	role_admin:    "Admin",
	outside_world: "Außenwelt",
	total:         "Gesamt",
	uncategorized: "Nicht kategorisiert",
	// calendar
	this_week:  "Diese Woche",
	this_month: "Dieser Monat",
	this_year:  "Dieses Jahr",
	Monday:     "Montag",
	Tuesday:    "Dienstag",
	Wednesday:  "Mittwoch",
	Thursday:   "Donnerstag",
	Friday:     "Freitag",
	Saturday:   "Samstag",
	Sunday:     "Sonntag",
	January:    "Januar",
	February:   "Februar",
	March:      "März",
	April:      "April",
	May:        "Mai",
	June:       "Juni",
	July:       "Juli",
	August:     "August",
	September:  "September",
	October:    "Oktober",
	November:   "November",
	December:   "Dezember",
}
