package localizations

import "genuine/core/localizations"

var dfault = localizations.Localization{
	"payments":                        "Payments",
	"categories":                      "Categories",
	"analysis":                        "Analysis",
	"balances":                        "Balances",
	"expenses":                        "Expenses",
	"by_period":                       "By period",
	"by_category":                     "By category",
	"admin_functions":                 "Admin functions",
	"users":                           "Users",
	"projects":                        "Projects",
	"previous":                        "Previous",
	"next":                            "Next",
	"logout":                          "Logout",
	"search":                          "Search",
	"search_results":                  "Search results",
	"filter":                          "Filter",
	"new":                             "New",
	"edit":                            "Edit",
	"save":                            "Save",
	"cancel":                          "Cancel",
	"delete":                          "Delete",
	"delete_confirmation":             "Delete confirmation",
	"delete_confirmation_description": "Delete confirmation description",
	"records_found":                   "Records found",
	"no_records_found":                "No records found",
	"record_saved_successfully":       "Record saved successfully",
	"id":                              "ID",
	"name":                            "Name",
	"amount":                          "Amount",
	"date":                            "Date",
	"category":                        "Category",
	"color":                           "Color",
	"payer":                           "Payer",
	"payee":                           "Payee",
	"description":                     "Description",
	"username":                        "Username",
	"password":                        "Password",
	"role":                            "Role",
	"role_normal":                     "Role normal",
	"role_admin":                      "Role admin",
	"outside_world":                   "Outside world",
	"total":                           "Total",
	"uncategorized":                   "Uncategorized",
	"debts":                           "Debts",
	"receivables":                     "Receivables",
	"total_expenses":                  "Total expenses",
	"user_amount":                     "User amount",
	"proportional_expenses":           "Proportional expenses",
	"sent_expenses":                   "Sent expenses",
	"sent_transfer":                   "Sent transfer",
	"received_transfer":               "Received transfer",
	"result":                          "Result",
	"this_week":                       "This week",
	"this_month":                      "This month",
	"this_year":                       "This year",
	"monday":                          "Monday",
	"tuesday":                         "Tuesday",
	"wednesday":                       "Wednesday",
	"thursday":                        "Thursday",
	"friday":                          "Friday",
	"saturday":                        "Saturday",
	"sunday":                          "Sunday",
	"january":                         "January",
	"february":                        "February",
	"march":                           "March",
	"april":                           "April",
	"may":                             "May",
	"june":                            "June",
	"july":                            "July",
	"august":                          "August",
	"september":                       "September",
	"october":                         "October",
	"november":                        "November",
	"december":                        "December",
}
